theme = 'adwaita-dark'

[editor]
# line-number = 'relative'
mouse = true
cursorline = true

[editor.cursor-shape]
insert = 'bar'
normal = 'block'

[editor.file-picker]
hidden = false

[editor.statusline]
separator = "|"
left = ['spinner', 'mode', 'spacer', 'version-control']
center = ['diagnostics', 'file-name', 'file-modification-indicator']
right = ['primary-selection-length', 'selections', 'separator', 'position', 'spacer', 'position-percentage']

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.insert]
C-space = 'completion'
