theme = 'adwaita-dark'

[editor]
mouse = true
cursorline = true
line-number = "relative"

[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.statusline]
# separator = "|"
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["version-control"]
right = ["diagnostics", "selections", "position", "position-percentage"]

[editor.indent-guides]
render = false
skip-levels = 0
# character = "⸽" # Some characters that work well: "▏", "┆", "┊", "⸽", "╎"

[editor.soft-wrap]
enable = true

[keys.insert]
C-space = 'completion'

[keys.normal.'\']
v = [''':sh tmux split-window -h -c "#{pane_current_path}" -l 33%''']
s = [''':sh tmux split-window -v -c "#{pane_current_path}" -l 33%''']
space = ['extend_to_line_bounds', ''':pipe-to tmux load-buffer - \; paste-buffer -dpr -t '{right-of}' \; send-keys -t '{right-of}' Enter''', 'move_visual_line_down']
l = [''':pipe-to tmux load-buffer - \; paste-buffer -dpr -t '{right-of}' \; send-keys -t '{right-of}' Enter''']
k = [''':pipe-to tmux load-buffer - \; paste-buffer -dpr -t '{up-of}' \; send-keys -t '{up-of}' Enter''']
j = [''':pipe-to tmux load-buffer - \; paste-buffer -dpr -t '{down-of}' \; send-keys -t '{down-of}' Enter''']
h = [''':pipe-to tmux load-buffer - \; paste-buffer -dpr -t '{left-of}' \; send-keys -t '{left-of}' Enter''']

[keys.select.'\']
l = [''':pipe-to tmux load-buffer - \; paste-buffer -dpr -t '{right-of}' \; send-keys -t '{right-of}' Enter''']
k = [''':pipe-to tmux load-buffer - \; paste-buffer -dpr -t '{up-of}' \; send-keys -t '{up-of}' Enter''']
j = [''':pipe-to tmux load-buffer - \; paste-buffer -dpr -t '{down-of}' \; send-keys -t '{down-of}' Enter''']
h = [''':pipe-to tmux load-buffer - \; paste-buffer -dpr -t '{left-of}' \; send-keys -t '{left-of}' Enter''']
