theme = 'adwaita-dark'

[editor]
# line-number = 'relative'
mouse = true
cursorline = true

[editor.cursor-shape]
insert = 'bar'
normal = 'block'

[editor.file-picker]
hidden = false

[editor.statusline]
separator = "|"
left = ['spinner', 'mode', 'separator', 'file-type', 'file-encoding', 'separator', 'spacer', 'version-control']
center = ['file-name', 'file-modification-indicator', 'diagnostics']
right = ['primary-selection-length', 'selections', 'separator', 'spacer', 'position-percentage', 'position', 'total-line-numbers']

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.insert]
# C-space = 'completion'
