theme = 'adwaita-dark'

[editor]
mouse = true
cursorline = true

[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.statusline]
separator = "|"
left = ['spinner', 'mode', 'spacer', 'version-control']
center = ['diagnostics', 'file-name', 'file-modification-indicator']
right = ['primary-selection-length', 'selections', 'separator', 'position', 'spacer', 'position-percentage']

[editor.indent-guides]
render = false
skip-levels = 0
# character = "⸽" # Some characters that work well: "▏", "┆", "┊", "⸽", "╎"

[editor.soft-wrap]
enable = true
